### ISSUE TITLE
[bug] Starter Repository -- Sandpit -- Cannot Create Storage Container

### ISSUE THREAD

**Issue by loispostula** [Azure/caf-terraform-landingzones#125]
**Describe the bug**
When applying the caf-launchpad with var in the starter repository (sandpit) the apply is failing due to Permissions error:

Problematic resources:
* `module.launchpad.module.storage_accounts["level0"].module.container["tfstate"].azurerm_storage_container.stg`
* `module.launchpad.module.storage_accounts["level1"].module.container["tfstate"].azurerm_storage_container.stg`
* `module.launchpad.module.storage_accounts["level2"].module.container["tfstate"].azurerm_storage_container.stg`
* `module.launchpad.module.storage_accounts["level3"].module.container["tfstate"].azurerm_storage_container.stg`
* `module.launchpad.module.storage_accounts["level4"].module.container["tfstate"].azurerm_storage_container.stg`

error messages:

```
Error: failed creating container: failed creating container: containers.Client#Create: Failure responding to requests: StatusCode=403 -- Original Error: autorest/azure: Service return an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation".\nRequestId:728d0834-601e-0485-e90144000000\nTime:2021-01-13T08:27:07.6770612Z"

   on /home/vscode/.terraform.cache/modules/launchpad/modules/storage_account/container/container.tf line 1, in resource "azurerm_storage_container" "stg":
     1. resource "azurerm_storage_container" "stg" {
```

My user is Owner of the subscription and I made sure that the date is well sync within the rover container

**Comment by Mhmccabe** [comment]
I also get the same error when using the DEMO configuration

**Comment by Sebas1337** [comment]
> **Describe the bug**
> When applying the caf-launchpad with var in the starter repository (sandpit) the apply is failing due to Permissions error:
> 
> Problematic resources:
> 
> * `module.launchpad.module.storage_accounts["level0"].module.container["tfstate"].azurerm_storage_container.stg`
> * `module.launchpad.module.storage_accounts["level1"].module.container["tfstate"].azurerm_storage_container.stg`
> * `module.launchpad.module.storage_accounts["level2"].module.container["tfstate"].azurerm_storage_container.stg`
> * `module.launchpad.module.storage_accounts["level3"].module.container["tfstate"].azurerm_storage_container.stg`
> * `module.launchpad.module.storage_accounts["level4"].module.container["tfstate"].azurerm_storage_container.stg`
> 
> error messages:
> 
> ```
> Error: failed creating container: failed creating container: containers.Client#Create: Failure responding to requests: StatusCode=403 -- Original Error: autorest/azure: Service return an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation".\nRequestId:728d0834-601e-0485-e90144000000\nTime:2021-01-13T08:27:07.6770612Z"
> 
>    on /home/vscode/.terraform.cache/modules/launchpad/modules/storage_account/container/container.tf line 1, in resource "azurerm_storage_container" "stg":
>      1. resource "azurerm_storage_container" "stg" {
> ```
> 
> My user is Owner of the subscription and I made sure that the date is well sync within the rover container

I got it working.

First delete your partially deployed config with 
`rover -lz /tf/caf/landingzones/caf_launchpad \
-launchpad \
-var-folder /tf/caf/landingzones/caf_launchpad/scenario/100 \
-a destroy`

After that go to you Azure portal and create a new Azure Active Directory User for the landingzone.
Then go to the subscription you use for deplyment and select IAM > Role Assignment > Add and add a 'Owner'-role for the new AD account.

Login in rover with the new AD account and run the script again:
`rover login`
`rover -lz /tf/caf/landingzones/caf_launchpad \
-launchpad \
-var-folder /tf/caf/landingzones/caf_launchpad/scenario/100 \
-a apply`

**Comment by arnaudlh** [comment]
@Sebas1337 , @Mhmccabe: In 2101 edition of the rover, we are adding a technical check to verify that you have the Owner role on the subscription which is a requirement.

**Comment by loispostula** [comment]
Indeed having redeploy with Owner permissions, we can see that this is working. It will be nice to have the check in the 2101 edition.

Thanks for the help
