### ISSUE TITLE
Failed at setting up launchpad 

### ISSUE THREAD

**Issue by carthikannayan** [Azure/caf-terraform-landingzones#127]
**Describe the bug**
Unable to deploy caf-landing zones for launchpad. It fails with the creation of Azure Active Directory Applications and role assignment. The other resources do get created. This happens when I initiate the Pipeline through Azure Devops.

This is exactly the same as https://github.com/Azure/caf-terraform-landingzones/issues/20

**To Reproduce**
1. Go to 'https://github.com/Azure/caf-terraform-landingzones/issues/20'
2. Click on 'https://github.com/Azure/caf-terraform-landingzones/issues/20.'

Error: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-01-21T23:01:55","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"5d068b83-b992-4cd5-922b-53d7cc90b193"}}]

  on identity.tf line 4, in resource "azuread_application" "launchpad":
   4: resource "azuread_application" "launchpad" {

**Expected behavior**
Azure Active Directory Applications and role assignment

This a critical aspect of the launchpad bootstrap process. The deployment creates an Azure AD Application named "caf_launchpad_level0" by default. The launchpad can be configured to create additional Azure AD Applications

The user deploying the launchpad is set to be the application owner
A Service Principal + random password is created for each Application - the data is then stored in the referenced keyvault as multiple secrets
Resource Access is assigned based on the aad_api_permissions object
Each application can be assigned one or multiple Azure AD roles through the aad_roles object - empty by default

Launchpad creation failed 
=================

2021-01-20T03:52:22.8517299Z Error: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2021-01-20T03:50:11","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"d9ce8e92-845d-4408-831d-5869306a912d"}}]
2021-01-20T03:52:22.8523886Z
2021-01-20T03:52:22.8524648Z on identity.tf line 4, in resource "azuread_application" "launchpad":
2021-01-20T03:52:22.8525414Z 4: resource "azuread_application" "launchpad" {
2021-01-20T03:52:22.8525618Z
2021-01-20T03:52:22.8525712Z
2021-01-20T03:52:22.8526487Z �[41mError on or near line 488: Error running terraform apply; exiting with status 2001�[0m
2021-01-20T03:52:22.8526763Z
2021-01-20T03:52:22.8526921Z @calling clean_up_variables
2021-01-20T03:52:22.8527115Z cleanup variables
2021-01-20T03:52:22.8610939Z ##[error]Bash exited with code '209'.
2021-01-20T03:52:22.8976284Z ##[section]Finishing: Initialize Launchpad for DEV environment

**Configuration (please complete the following information):**
 - OS and version: [e.g. Windows 10 1909]
 - Version of the rover[e.g. 22]
 - Version of the landing zone[e.g. 11]

**Additional context**

**Comment by arnaudlh** [comment]
hi @carthikannayan you need AAD privileges to run the launchpad scenario 200 as per [this](https://github.com/Azure/caf-terraform-landingzones/blob/master/landingzones/caf_launchpad/scenario/200/readme.md)


| Component          | Privileges                     |
|--------------------|--------------------------------|
| Active Directory   | Application Administrator role |
| Azure subscription | Subscription owner             |

can you please confirm?

**Comment by carthikannayan** [comment]
hi @arnaudlh : Thanks for your quick response, I followed https://github.com/Azure/caf-terraform-landingzones/blob/master/documentation/enterprise/bootstrap_account_provisioning.md 

Setup permissions for Azure AD Graph  and Microsoft Graph (Application, Delegated Permissions) That worked. I will now continue to build on the other  levels to see if that works. Thanks for your help! Meanwhile, are you able to share a sample CI file (like the one you used in your video)  https://youtu.be/r6RUiFOl-JU

Thank you!

**Comment by n8london** [comment]
@arnaudlh Microsoft has deprecated Graph API. Is there an alternative?

![image](https://user-images.githubusercontent.com/50328411/136715354-fffc0dea-d81b-499f-ad57-61e3b8618b23.png)
