### ISSUE TITLE
[bug] Cannot destroy launchpad from Getting Started Guide

### ISSUE THREAD

**Issue by jshchn** [Azure/caf-terraform-landingzones#140]
**Describe the bug**
I was following along with the [Getting Started](https://github.com/Azure/caf-terraform-landingzones/blob/master/documentation/getting_started/getting_started.md) tutorial without issue. I had destroyed the 'Networking Scenario' and the 'Foundations' landingzones, no issues either. I left it in that state for a day. After a day, I did a rover login again and wanted to cleanup the launchpad landingzone. I couldn't destroy it and I am seeing the error message below.

"Authentication failure. This may be caused by either invalid account key, connection string or sas token value provided for your storage account.
                    
landing zone already deleted"

**To Reproduce**
Same as above. Following the Getting Started guide and leaving it open for a day before trying to destroy the Launchpad landingzone.

**Expected behavior**
I expected that I would be able to destroy the Launchpad landingzone even after a day.

**Screenshots**
![image](https://user-images.githubusercontent.com/3598877/108302549-28bc3200-71df-11eb-956d-cd02aba1afc9.png)

**Configuration (please complete the following information):**
 - OS and version: [e.g. Windows 10 Enterprise 19042.804]
 - Version of the rover: 2102.0100
 - Version of the landing zone (How do I check this?)

**Additional context**
None.

**Comment by arnaudlh** [comment]
hi @jshchn this is usually due to clock skew between container and laptop... can you try either rebooting the laptop of running sudo hwclock -s in your WSL distro.

**Comment by jshchn** [comment]
Thanks @arnaudlh, restarting my laptop did fix it! 👍
