### ISSUE TITLE
[bug] Error on or near line 182: the current account must have Owner privilege on the subscription to deploy launchpad.; exiting with status 2

### ISSUE THREAD

**Issue by RajendraVenkata** [Azure/caf-terraform-landingzones#141]
**Describe the bug**
while executing the below command:
----------------------------------------------------------------------------------
rover -lz /tf/caf/landingzones/caf_launchpad \
    -launchpad \
    -var-folder /tf/caf/landingzones/caf_launchpad/scenario/100 \
    -parallelism=30 \
    -a apply
----------------------------------------------------------------------------------

I get the following error:

 Expanding variable files: /tf/caf/landingzones/caf_launchpad/scenario/100/*.tfvars
@calling verify_azure_session
Checking existing Azure session
@calling process_target_subscription
Set TF_VAR_tfstate_subscription_id variable to current session's subscription.
caf_command launchpad
target_subscription_id caad40e7-aeb4-ZZZZZZZZZZZZZZ
TF_VAR_tfstate_subscription_id caad40e7-aeb4-ZZZZZZZZZZZZZZZ
Resources from this landing zone are going to be deployed in the following subscription:
{
  "environmentName": "AzureCloud",
  "homeTenantId": "781d7403-47b4-4193-ZZZZZZZZZZZZZ",
  "id": "caad40e7-aeb4-4c18-ZZZZZZZZZZZZ",
  "isDefault": true,
  "managedByTenants": [],
  "name": "ZZZZZZZZZZZZ",
  "state": "Enabled",
  "tenantId": "781d7403-47b4-4193-ZZZZZZZZZZZZZZZZ",
  "user": {
    "name": "ZZZZZZZZZZZZZZ@hotmail.com",
    "type": "user"
  }
}
debug: caad40e7-aeb4-4c18-ZZZZZZZZZZZZZ
Tfstates subscription set to caad40e7-aeb4-YYYY-82d5-XXXXXXXXXXXXXX (XXXXXXXXXXXX)

mode                          : 'launchpad'
terraform command output file : ''
tf_action                     : 'apply'
command and parameters        : '-var-file /tf/caf/landingzones/caf_launchpad/scenario/100/configuration.tfvars -var-file /tf/caf/landingzones/caf_launchpad/scenario/100/dynamic_secrets.tfvars -var-file /tf/caf/landingzones/caf_launchpad/scenario/100/iam_role_mapping.tfvars -var-file /tf/caf/landingzones/caf_launchpad/scenario/100/keyvaults.tfvars -var-file /tf/caf/landingzones/caf_launchpad/scenario/100/storage_accounts.tfvars'

level (current)               : 'level0'
environment                   : 'sandpit'
workspace                     : 'tfstate'
tfstate                       : 'caf_launchpad.tfstate'
tfstate subscription id       : 'caad40e7-aeb4-4c18-YYYYY-XXXXXXXXXX'
target subscription           : 'RajXXXXXXXXXXXX'

@calling process_actions
@calling verify_parameters
landingzone                   : '/tf/caf/landingzones/caf_launchpad'
@calling_deploy
@calling get_storage_id
@calling_get_logged_user_object_id
 - logged in user objectId: 63de8ec5-3db3-4fe1-YYYYY-XXXX (XXXXX.XXXXXXXXXXX#EXT#@YYYYYYYYYYYhotmail.onmicrosoft.com)
Initializing state with user: XXXXXXXXXXXXX.com#EXT#@YYYYYYYYYYYYY.onmicrosoft.com
No launchpad found.
Deploying from scratch the launchpad
@calling initialize_state
Checking required permissions
@checking if current user (object_id: 63de8ec5-3db3-4fe1-ZZZZZZZZZZZZZZZZZZZZZ) is Owner of the subscription - only for launchpad
Error on or near line 182: the current account must have Owner privilege on the subscription to deploy launchpad.; exiting with status 2

**To Reproduce**
Execute the command from Rover on VisualStudio Code.

rover -lz /tf/caf/landingzones/caf_launchpad \
    -launchpad \
    -var-folder /tf/caf/landingzones/caf_launchpad/scenario/100 \
    -parallelism=30 \
    -a apply

**Expected behavior**
Should create the resources and exit with no error.

**Screenshots**
Attached screenshot with error

**Configuration (please complete the following information):**
 - OS and version: Windows 10
 - Version of the rover:  aztfmod/rover:2102.0100
 - Version of the landing zone:latest

![image](https://user-images.githubusercontent.com/881366/108631256-ef115280-748e-11eb-867b-2f32ea0431b3.png)

**Comment by cchiriac518** [comment]
I had the same issue and it's as the error says. You just have to add yourself as an Owner on your subscription. I was added as an Administrator on my subscription and I've added myself as Owner and after that it worked

**Comment by RajendraVenkata** [comment]
Hi,
Can you please tell me how to add myself as owner? From the screenshot below it looks like I am Account admin
![image](https://user-images.githubusercontent.com/881366/108717615-7cae7a00-7543-11eb-8d8c-f9b88ee4b000.png)

**Comment by cchiriac518** [comment]
Can't remember exactly. I remember I've google it. https://www.msb365.blog/?p=83#:~:text=Azure%20portal%2B&text=On%20the%20Hub%20menu%2C%20select,user%2C%20and%20then%20click%20Select.

**Comment by RajendraVenkata** [comment]
Hi cchiriac518,

Finally it worked. I added my user id again as owner.

![image](https://user-images.githubusercontent.com/881366/108721468-095b3700-7548-11eb-9da3-777755d1ab7a.png)

**Comment by RajendraVenkata** [comment]
Post adding the userid as owner to the subscription it works now.

Thanks and Regards
Rajendra
