### ISSUE TITLE
[bug]invalid count argument - launchpad module

### ISSUE THREAD

**Issue by olofspango** [Azure/caf-terraform-landingzones#148]
**Describe the bug**
I was trying to use the set up the [starter-temlate for CAF](https://github.com/Azure/caf-terraform-landingzones-starter), following the steps found [here](https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/configuration/demo/README.md). 

Rover fails in 'terraform plan' step. 
![image](https://user-images.githubusercontent.com/29732023/110963088-f6bb6d00-8351-11eb-9a9e-958bfd638c13.png)

> Error: Invalid count argument
> 
>   on /home/vscode/.terraform.cache/modules/launchpad/locals.tf line 2, in resource "random_string" "prefix":
>    2:   count = try(var.global_settings.prefix, null) == null ? 1 : 0
> 
> The "count" value depends on resource attributes that cannot be determined
> until apply, so Terraform cannot predict how many instances will be created.
> To work around this, use the -target argument to first apply only the
> resources that the count depends on.
> 

**Workaround**
The issue appears to reside within the launchpad module. I downgraded the version of the "azftmod/caf/azurerm" from ~>5.2.0 to ~>5.1.0, which solved the problem.

**To Reproduce**

 rover -lz /tf/caf/public/landingzones/caf_launchpad/ \
 -launchpad \
 -var-folder /tf/caf/configuration/demo/level0/launchpad \
 -parallelism 30 \
 -level level0 \
 -env demo \
 -a plan

**Expected behavior**
Expect rover to successfully complete the terraform plan step.

**Configuration (please complete the following information):**
 - Win10, running in DevContainer

**Comment by arnaudlh** [comment]
hi @olofspango, I will be working on it today. thanks for reporting!

**Comment by arnaudlh** [comment]
Please make sure to use latest: https://github.com/Azure/caf-terraform-landingzones/releases/tag/2102.0.1 and let us know if it resolves!

**Comment by olofspango** [comment]
Thanks, tested and I can confirm that the latest release resolved the issue for me.
