### ISSUE TITLE
Add resource_groups and virtual_machines in the output

### ISSUE THREAD

**Issue by xpillons** [Azure/caf-terraform-landingzones#150]
**Describe the solution you'd like**
In order to extend a Level3 landing zone to create Ansible inventory files and configuration, I need to access resource_groups, public IPs and virtual machines names. The current output doesn't contains any RG nor VMs.

One way of fixing this will be to update the caf_solutions/locals.remote_tfstates.tf by adding this in the combined

```
     resource_groups                  = merge(local.remote.resource_groups, tomap({ (var.landingzone.key) = module.caf.resource_groups }))
    virtual_machines                 = merge(local.remote.virtual_machines, tomap({ (var.landingzone.key) = module.caf.virtual_machines }))
```

this in the remote
```
    virtual_machines = {
      for key, value in try(var.landingzone.tfstates, {}) : key => merge(try(data.terraform_remote_state.remote[key].outputs.virtual_machines[key], {}))
    }
```

and this in the output

```
output resource_groups {
  value   = local.combined.resource_groups
}
output virtual_machines {
  value     = local.combined.virtual_machines
  sensitive = false
}
```

**Comment by arnaudlh** [comment]
closing as merged - thanks @xpillons
