### ISSUE TITLE
getting Error: Invalid count argument

### ISSUE THREAD

**Issue by jwaltireland** [Azure/caf-terraform-landingzones#154]
I'm following the instructions in the starter video, and when I run the first rover deploy command to deploy the level0 launchpad, I'm getting this error running the command:

rover -lz /tf/caf/landingzones/caf_launchpad \
  -launchpad -var-folder \
  /tf/caf/landingzones/caf_launchpad/scenario/100 \
  -a apply

NOTE:  I did have to add 'public' in the path:
rover -lz /tf/caf/public/landingzones/caf_launchpad \
  -launchpad -var-folder \
  /tf/caf/public/landingzones/caf_launchpad/scenario/100 \
  -a apply

Error: Invalid count argument

  on /home/vscode/.terraform.cache/modules/launchpad/locals.tf line 2, in resource "random_string" "prefix":
   2:   count = try(var.global_settings.prefix, null) == null ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

Error: Invalid count argument

  on /home/vscode/.terraform.cache/modules/launchpad/locals.tf line 10, in resource "random_string" "alpha1":
  10:   count = try(var.global_settings.prefix, null) == null ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

**Comment by ClaudioTorresAcevedo** [comment]
check #148 same.

**Comment by arnaudlh** [comment]
Please make sure to use latest: https://github.com/Azure/caf-terraform-landingzones/releases/tag/2102.0.1 and let us know if it resolves!
