### ISSUE TITLE
Scenerios 300 and 400 missing from caf_launchpad 

### ISSUE THREAD

**Issue by jonclyde** [Azure/caf-terraform-landingzones#156]
Scenerios 300 and 400 followings are missing from caf_launchpad (caf-terraform-landingzones\landingzones\caf_launchpad\scenario) but still included in documentation.

**Comment by rom1gal** [comment]
UPing it ;)

**Comment by ps23** [comment]
Any update on that?

**Comment by arnaudlh** [comment]
Will remove from documentation in the meanwhile :)
