### ISSUE TITLE
[bug] Role missing in Azure Active Directory

### ISSUE THREAD

**Issue by cedrox** [Azure/caf-terraform-landingzones#157]
**Describe the bug**
Role missing in Azure Active Directory

**To Reproduce**
1. Run sandpit from version 2102.0.1 and starter 2101.0.0
2. Azure plan ok 
3. Azure apply fail on command 
export environment=sandpit
rover -lz /tf/caf/public/landingzones/caf_launchpad   -var-folder /tf/caf/configuration/${environment}/level0/launchpad   -parallelism 30   -level level0   -env ${environment}   -launchpad   -a apply

**Expected behavior**
Deploy the caf_launchpad

**Logs**
module.launchpad.azurerm_bastion_host.host["launchpad_host"]: Still creating... [6m10s elapsed]
module.launchpad.module.virtual_machines["bastion_host"].azurerm_linux_virtual_machine.vm["linux"]: Still creating... [40s elapsed]
module.launchpad.azurerm_bastion_host.host["launchpad_host"]: Still creating... [6m20s elapsed]
module.launchpad.module.virtual_machines["bastion_host"].azurerm_linux_virtual_machine.vm["linux"]: Creation complete after 48s [id=/subscriptions/[sub-id]/resourceGroups/fpzs-rg-launchpad-bastion/providers/Microsoft.Compute/virtualMachines/fpzs-vm-bastion]
module.launchpad.azurerm_bastion_host.host["launchpad_host"]: Creation complete after 6m23s [id=/subscriptions/[sub-id]/resourceGroups/fpzs-rg-launchpad-bastion/providers/Microsoft.Network/bastionHosts/fpzs-bast-bastion]
module.launchpad.module.bastion_host_diagnostics["launchpad_host"].azurerm_monitor_diagnostic_setting.diagnostics["operations"]: Creating...
module.launchpad.module.bastion_host_diagnostics["launchpad_host"].azurerm_monitor_diagnostic_setting.diagnostics["operations"]: Creation complete after 2s [id=/subscriptions/[sub-id]/resourceGroups/fpzs-rg-launchpad-bastion/providers/Microsoft.Network/bastionHosts/fpzs-bast-bastion|operational_logs_and_metrics]
Terraform apply return code: 0
Terraform returned errors:

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'Directory Readers'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe/members/accea7bc-3b3e-4fd9-9207-3c19a2434cca/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:34",
      "request-id": "8a2aa31d-6043-4475-a592-2095e1d14f46",
      "client-request-id": "8a2aa31d-6043-4475-a592-2095e1d14f46"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'Directory Readers'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe/members/e14396cf-08c3-4df1-88c8-fc7b023ae967/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:34",
      "request-id": "44b218b4-77f8-433f-b15c-6d50d8f02de2",
      "client-request-id": "44b218b4-77f8-433f-b15c-6d50d8f02de2"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'Application Developer'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/4d09e349-be57-4888-b6d0-f6c5ababe40d/members/f6543891-f33d-4314-b991-be4af1ad7c42/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '4d09e349-be57-4888-b6d0-f6c5ababe40d' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:35",
      "request-id": "5d31de7a-4ff9-4efb-a783-b1cd335f9d55",
      "client-request-id": "5d31de7a-4ff9-4efb-a783-b1cd335f9d55"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'User Administrator'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/fc7712d8-2e23-4ac0-afd9-f9e93aacff94/members/f6543891-f33d-4314-b991-be4af1ad7c42/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource 'fc7712d8-2e23-4ac0-afd9-f9e93aacff94' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:34",
      "request-id": "bd710583-e6d9-4dc1-830f-c0402b3edbc7",
      "client-request-id": "bd710583-e6d9-4dc1-830f-c0402b3edbc7"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'Directory Readers'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe/members/839e2ee9-2eb4-4867-b7a0-9975a3b8d190/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:35",
      "request-id": "acbcab75-ce34-40e9-abab-f1b6c2622a21",
      "client-request-id": "acbcab75-ce34-40e9-abab-f1b6c2622a21"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role 'Directory Readers'
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe/members/f1177bb2-c6a5-44f1-83f6-1cdf3275c8fc/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:34",
      "request-id": "9593f559-6b04-4495-bbe6-7f1666c6e524",
      "client-request-id": "9593f559-6b04-4495-bbe6-7f1666c6e524"
    }
  }
})

Error: Error running command '/home/vscode/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts/set_ad_role.sh': exit status 1. Output: Directory role ''
 - uri: https://graph.microsoft.com/v1.0/directoryRoles/3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe/members/f6543891-f33d-4314-b991-be4af1ad7c42/$ref
ERROR: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '3e3c2e7d-941f-40d0-adf0-aaf8ea5efffe' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2021-03-29T20:39:35",
      "request-id": "3d997b9b-13e0-462f-ba8d-bfa714c103c7",
      "client-request-id": "3d997b9b-13e0-462f-ba8d-bfa714c103c7"
    }
  }
})

Error on or near line 212: Error running terraform apply; exiting with status 2001

@calling clean_up_variables
cleanup variables
clean_up backend_files

**Configuration (please complete the following information):**
 - OS and version: [Windows 10 20H2]
 - Version of the landing zone[2102.0.1 and starter 2101.0.0]

**Comment by cedrox** [comment]
This script is causing the issues
```

#!/bin/bash

set -e

function enable_directory_role {
    # Verify the AD_ROLE_NAME has been activated in the directory
    # Permissions required - https://docs.microsoft.com/en-us/graph/api/directoryrole-post-directoryroles?view=graph-rest-1.0&tabs=http#permissions

    echo "Enabling directory role: ${AD_ROLE_NAME}"
    ROLE_ID=$(az rest --method Get --uri https://graph.microsoft.com/v1.0/directoryRoleTemplates -o json | jq -r '.value[] | select(.displayName == "'"$(echo ${AD_ROLE_NAME})"'") | .id')

    URI="https://graph.microsoft.com/v1.0/directoryRoles"

    JSON=$( jq -n \
                --arg role_id ${ROLE_ID} \
            '{"roleTemplateId": $role_id}' ) && echo " - body: $JSON"


    az rest --method POST --uri $URI --header Content-Type=application/json --body "$JSON"

}

echo "Directory role '${AD_ROLE_NAME}'"


# Add service principal to AD Role

export ROLE_AAD=$(az rest --method Get --uri https://graph.microsoft.com/v1.0/directoryRoles -o json | jq -r '.value[] | select(.displayName == "'"$(echo ${AD_ROLE_NAME})"'") | .id')

if [ "${ROLE_AAD}" == '' ]; then
    enable_directory_role
    export ROLE_AAD=$(az rest --method Get --uri https://graph.microsoft.com/v1.0/directoryRoles -o json | jq -r '.value[] | select(.displayName == "'"$(echo ${AD_ROLE_NAME})"'") | .id')
fi


case "${METHOD}" in
    POST)
        URI=$(echo  "https://graph.microsoft.com/v1.0/directoryRoles/${ROLE_AAD}/members/\$ref") && echo " - uri: $URI"

        # grant AAD role to the AAD APP
        JSON=$( jq -n \
            --arg uri_role "https://graph.microsoft.com/v1.0/directoryObjects/${SERVICE_PRINCIPAL_OBJECT_ID}" \
            '{"@odata.id": $uri_role}' ) && echo " - body: $JSON"

        az rest --method ${METHOD} --uri $URI --header Content-Type=application/json --body "$JSON"

        echo "Role '${AD_ROLE_NAME}' assigned to azure ad application"
        ;;
    DELETE)
        URI=$(echo  "https://graph.microsoft.com/v1.0/directoryRoles/${ROLE_AAD}/members/${SERVICE_PRINCIPAL_OBJECT_ID}/\$ref") && echo " - uri: $URI"
        az rest --method ${METHOD} --uri ${URI}
        echo "Role '${AD_ROLE_NAME}' unassigned to azure ad application ${SERVICE_PRINCIPAL_OBJECT_ID}"
        ;;
esac


```



https://docs.microsoft.com/en-us/graph/api/directoryrole-post-directoryroles?view=graph-rest-1.0&tabs=http#permissions

I am tenant Global administrator

When I try to activate directory role: Directory Readers, here's the error.

vscode@9d4b6adf6b23:~/.terraform.cache/modules/launchpad/modules/azuread/roles/scripts$ az rest --method POST --uri $URI --header Content-Type=application/json --body "$JSON"
Bad Request({
  "error": {
    "code": "Request_BadRequest",
    "message": "A conflicting object with one or more of the specified property values is present in the directory.",
    "innerError": {
      "date": "2021-03-30T07:11:40",
      "request-id": "93313fb2-5179-429c-9786-01428d5b8b4b",
      "client-request-id": "93313fb2-5179-429c-9786-01428d5b8b4b"
    }
  }
})

I see the role in AAD...

**Comment by sketabchi-mobiz** [comment]
@LaurentLesle @cedrox I had a very similar issue when the service principal under which the rover was working was missing the following permissions: 
 [Permissions](/graph/permissions-reference).

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Delegated (work or school account) | RoleManagement.ReadWrite.Directory, Directory.AccessAsUser.All    |
|Delegated (personal Microsoft account) | Not supported.    |
|Application | RoleManagement.ReadWrite.Directory |

Please see [here](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-directoryroles?view=graph-rest-1.0&tabs=http#permissions):

https://docs.microsoft.com/en-us/graph/api/directoryrole-post-directoryroles?view=graph-rest-1.0&tabs=http#permissions

**Comment by cedrox** [comment]
@sketabchi-mobiz, do you still have the problem ? 
I don't have the problem anymore on my side...
