### ISSUE TITLE
[bug] Solution landing zones not inheriting tags from launchpad properly

### ISSUE THREAD

**Issue by davesee** [Azure/caf-terraform-landingzones#162]
**Describe the bug**
Levels 1+ that utilize the caf_solution landing zone do not inherit the launchpad tags. This is critical since the environment tag is not copied over and creates an inconsistent resource tagging result.

**To Reproduce**
1. Deploy launchpad
2. Deploy subsequent level using caf_solution landing zone.

**Expected behavior**
The level1+ deployments should have the same tags as level 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/68443470/115121744-4bba5680-9f82-11eb-9292-bbb30b6332f6.png)

![image](https://user-images.githubusercontent.com/68443470/115121769-71dff680-9f82-11eb-909d-8536a6e6cfc2.png)

**Configuration (please complete the following information):**
 - OS version Windows 10
 - Rover version aztfmod/rover:0.13.6-2103.0304
 - Version of the landing zone 5.3.0

**Comment by arnaudlh** [comment]
closing as merged into master
