### ISSUE TITLE
[bug] Unable to provision shared_services 100 scenario

### ISSUE THREAD

**Issue by martinhacker1965** [Azure/caf-terraform-landingzones#170]
**Describe the bug**
Attempt to provision the shared_services 100 scenario fails with error.

**Steps to reproduce**

1. Deploy launchpad using 100 scenario
rover -lz /tf/caf/caf_launchpad \
  -var-folder /tf/caf/caf_launchpad/scenario/100 \
  -parallelism 30 \
  -level level0 \
  -env sandpit \
  -launchpad \
  -a apply

Succeeds with no error. Creates level0 remote state file caf_launchpad.tfstate

2. Deploy foundations using 100-passthrough scenario.
rover -lz /tf/caf/caf_solution \
  -var-folder /tf/caf/caf_solution/scenario/foundations/100-passthrough \
  -parallelism 30 \
  -level level1 \
  -env sandpit \
  -a apply

Succeeds with no error. Creates level1 remote state file caf_solution.tfstate

3. Deploy shared_services using 100 scenario.
rover -lz /tf/caf/caf_solution \
  -var-folder /tf/caf/caf_solution/scenario/shared_services/100 \
  -parallelism 30 \
  -level level2 \
  -env sandpit \
  -a plan

Fails with error. Creates 156 byte level2 remote state file caf_solution.tfstate and similar in level1.

**Expected behaviour**
Step 2 creates level1 remote state file caf_foundations.tfstate
Step 3 creates level2 remote state file caf_shared_services.tfstate
Plan succeeds and subsequent apply successful.

**Logs**
Terraform returned errors:
╷
│ Error: Unsupported attribute
│ 
│   on locals.remote_tfstates.tf line 35, in locals:
│   35:   global_settings = merge(data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.objects[var.landingzone.global_settings_key].global_settings, var.global_settings)
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "objects".
╵
╷
│ Error: Unsupported attribute
│ 
│   on locals.remote_tfstates.tf line 44, in locals:
│   44:     diagnostics_definition = merge(data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.objects[var.landingzone.global_settings_key].diagnostics.diagnostics_definition, var.diagnostics_definition)
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "objects".
╵
╷
│ Error: Unsupported attribute
│ 
│   on locals.remote_tfstates.tf line 60, in locals:
│   60:     storage_accounts     = data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.objects[var.landingzone.global_settings_key].diagnostics.storage_accounts
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "objects".
╵
╷
│ Error: Unsupported attribute
│ 
│   on locals.remote_tfstates.tf line 61, in locals:
│   61:     log_analytics        = data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.objects[var.landingzone.global_settings_key].diagnostics.log_analytics
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "objects".
╵
╷
│ Error: Unsupported attribute
│ 
│   on locals.remote_tfstates.tf line 62, in locals:
│   62:     event_hub_namespaces = data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.objects[var.landingzone.global_settings_key].diagnostics.event_hub_namespaces
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "objects".
╵
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 54, in locals:
│   54:     data.terraform_remote_state.remote[var.landingzone.global_settings_key].outputs.tfstates
│     ├────────────────
│     │ data.terraform_remote_state.remote is object with 1 attribute "caf_foundations"
│     │ var.landingzone.global_settings_key is "caf_foundations"
│ 
│ This object does not have an attribute named "tfstates".
╵
Error on or near line 249: Error running terraform plan; exiting with status 2000

**Comment by arnaudlh** [comment]
Martin, you need to use instructions as detailed in the starter repo: https://github.com/Azure/caf-terraform-landingzones-starter/tree/starter/configuration/demo.
Baseline is you need to specify the ```-tfstate caf_foundations.tfstate``` argument to specify a file name under which the state will be stored, and it must be this same name that you will use in the 

```
landingzone = {
  backend_type        = "azurerm"
  global_settings_key = "caf_foundations"
  level               = "level2"
  key                 = "shared_services"
  tfstates = {
    caf_foundations = {
      level   = "lower"
      tfstate = "caf_foundations.tfstate"
    }
  }
}
```

**Comment by martinhacker1965** [comment]
Thanks @arnaudlh I found this -tfstate argument follwing further reading and pleased to say it's all now working.
