### ISSUE TITLE
[bug] update documentation for rover apply commands

### ISSUE THREAD

**Issue by GlennChia** [Azure/caf-terraform-landingzones#203]
**Describe the bug**
Following the rover documentation at `caf_launchpad/readme.md` to deploy the launchpad produces an error stating that the file path is incorrect. The proposed fix is to change the file paths in the command.

**To Reproduce**
1. Clone the repository
2. Change directory to the root and run `rover login`
3. Then run the rover command for simple scenario that is specified in the documentation at `caf_launchpad/readme.md` to deploy the launchpad
![image](https://user-images.githubusercontent.com/31919569/121011947-ca38b500-c7c9-11eb-8bc3-c6306c67c86d.png)

3. This results in the following error: `/tf/rover/functions.sh: line 166: cd: /tf/caf/landingzones/caf_launchpad: No such file or directory Error on or near line 166; exiting with status 1`
![image](https://user-images.githubusercontent.com/31919569/121012105-f48a7280-c7c9-11eb-889e-441429afc6ac.png)

**Expected behavior**
Change the command to the following to fix
```bash
rover -lz /tf/caf/caf_launchpad \
    -launchpad \
    -var-folder /tf/caf/caf_launchpad/scenario/100 \
    -parallelism=30 \
    -a apply
```

This is because the directory structure is as follows:

![image](https://user-images.githubusercontent.com/31919569/121013864-f5bc9f00-c7cb-11eb-92e3-0016cd355340.png)

**Screenshots**
Screenshots shown above

**Configuration (please complete the following information):**
 - Version of the rover: aztfmod/rover:0.15.4-2105.2603
 - Landing zone tag: 2106.1

**Additional context**

**Comment by arnaudlh** [comment]
Thanks for your contribution @GlennChia
