### ISSUE TITLE
[feature] Missing support for azurerm_firewall_policy_rule_collection_groups

### ISSUE THREAD

**Issue by rmul** [Azure/caf-terraform-landingzones#219]
I want to create firewall policy rule groups.
In the upstream terraform-azurerm-caf module there is support for creating firewall policy rule groups (from tag 5.3.3), but the current solution does not implement that yet.

We need to add a variable azurerm_firewall_policy_rule_collection_groups and pass that on to the local.networking so the aztfmod/caf/azurerm module can process it.

See https://github.com/aztfmod/terraform-azurerm-caf/blob/master/examples/networking/firewall/103-firewall-policies/configuration.tfvars as example implementation.

**Comment by arnaudlh** [comment]
thanks @rmul, this is in 2106 next release, to be released very soon!
