### ISSUE TITLE
Upgrade to Module version 0.3.3 for caf-eslz addon

### ISSUE THREAD

**Issue by hriaz** [Azure/caf-terraform-landingzones#222]
https://github.com/Azure/caf-terraform-landingzones/blob/0877d95706bb17b06410b1a451d0e98827763153/caf_solution/add-ons/caf_eslz/enterprise_scale.tf#L5

According to [Enterprise-scale repo](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/releases/tag/v0.3.3) the latest release is 0.3.3. Shouldn't this be changed here?

**Comment by arnaudlh** [comment]
hi @hriaz this is line for next rel. thanks for your issue!

**Comment by arnaudlh** [comment]
@hriaz: you can have a look at the branch eslz.0.3.3 if you start from scratch, and use the following example in the starter kit: https://github.com/Azure/caf-terraform-landingzones-starter/tree/AL-contoso/configuration/contoso/platform/demo/level1/eslz 
If you are migrating from 2107.1 (eslz 0.1.2) the upgrade notes will be pending.

**Comment by golvteppe** [comment]
Will there also be new variables for accessing the new features after upgrade in the enterprise_scale module? ""configure_management_resources" for example

**Comment by LaurentLesle** [comment]
@golvteppe at the moment the external resources can be created from the CAF Terraform and referenced in the archetypes_config_overrides.tfvars 
![image](https://user-images.githubusercontent.com/4702224/129708921-3026220a-479c-48c7-88fe-251ec2ffe6c5.png)

**Comment by pmatthews05** [comment]
@LaurentLesle as ESLZ is now at 0.4.0 is there plans on getting it upgrade to that instead? I've been using the eslz.0.3.3 branch upto now.

**Comment by arnaudlh** [comment]
> @LaurentLesle as ESLZ is now at 0.4.0 is there plans on getting it upgrade to that instead? I've been using the eslz.0.3.3 branch upto now.

2111.0 is on 3.3, and we are planning 1.0.x for 2111.1
