### ISSUE TITLE
[feature] Please enable blob storage versioning for TFSTATE Storage accounts

### ISSUE THREAD

**Issue by GoodDingo** [Azure/caf-terraform-landingzones#232]
**Is your feature request related to a problem? Please describe.**
Terraform cache and/or Rover got to a weird state (that was solved by deleting whole terraform.cache) but during that `rover ... -a plan` "updated" my state-file to an "empty" state (only initial json with empty resources and output). Hopefully this happened during experimentation phase where I'm able to delete all the stale resources by hand. I have no idea how to reproduce this (and don't even want to :-) ).

**Describe the solution you'd like**
I wanted to go to `level1` storage account, `tstate` container and restore the previous version of my state (`eslz.tfstate`) but there was none. This should be possible and enabled by default in my opinion. Now I have a lot of management groups and policies all over the place without a state thanks to some bug or cache issue.

**Describe alternatives you've considered**
I'm not sure where exactly in Launchpad are Storage Accounts are created, but level0..level4 SA should be created with [option versioning_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#versioning_enabled). If not by default, at least as a bool configuration option in a launchpad.

**Additional context**
It's relevant only to Launchpad and `l0 .. l4` storage accounts.

**Comment by arnaudlh** [comment]
hi @GoodDingo, this is a configuration time item that you can add using: 

```hcl
blob_properties = {
      versioning_enabled                = true
    }
```

That could be a good candidate to be included by default in the templates with addition to ```container_delete_retention_policy``` and ```delete_retention_policy```, to have something like that:

```

storage_accounts = {
  level0 = {
    name                     = "level0"
    resource_group_key       = "level0"
    account_kind             = "BlobStorage"
    account_tier             = "Standard"
    account_replication_type = "RAGRS"
    tags = {
      ## Those tags must never be changed after being set as they are used by the rover to locate the launchpad and the tfstates.
      # Only adjust the environment value at creation time
      tfstate     = "level0"
      environment = "sandpit"
      launchpad   = "launchpad"
      ##
    }
    blob_properties = {
      versioning_enabled                = true
      container_delete_retention_policy = 7
      delete_retention_policy           = 7
    }
    containers = {
      tfstate = {
        name = "tfstate"
      }
    }
  }
...
}
```
