### ISSUE TITLE
[bug] aks-secure-baseline add-on doesn't work when using an user-assigned identity (user-msi)

### ISSUE THREAD

**Issue by swetha-sundar** [Azure/caf-terraform-landingzones#237]
**Issue**
aks-secure-baseline add-on doesn't work when using an user-assigned identity (user-msi)

**To Reproduce**
1. Create an AKS Cluster using UserAssigned identity
2. Apply the aks-secure-baseline (v1 or v2) add-on on the configuration
3. See error in the below screenshot 

**Expected behavior**
The principal id value cannot be null when you do a role assignment. This value needs to be fetched from managed identity  and used while doing the role assignment using the user msi.

**Screenshots**
<img width="1174" alt="Add-on_UserMSI-AKS" src="https://user-images.githubusercontent.com/42051002/128974010-bab9d9c5-2746-429f-94a0-b3d1da94dd6d.png">

**Comment by swetha-sundar** [comment]
PR submitted - https://github.com/Azure/caf-terraform-landingzones/pull/238

**Comment by rickychew77** [comment]
Hello, I am having another issue after the PR merged (screenshot below). Had no error earlier while running this `aks_secure_baseline_v2`. 

![image](https://user-images.githubusercontent.com/41740185/130387084-f1243cfc-fe2b-4e5f-aa8c-b5af0ee701b3.png)

**Comment by arnaudlh** [comment]
Should all be fixed in 2108.0, let us know!
