### ISSUE TITLE
[bug] caf_eslz upgrade issue

### ISSUE THREAD

**Issue by PrudviS** [Azure/caf-terraform-landingzones#257]
custom_landing_zones variable expects subscription map to be passed in version 2108.0, which was not the case in version 2106.0

If this is passed and the subscription key is set to null, plan errors with the message "Invalid Index"

![image](https://user-images.githubusercontent.com/65976930/135077069-43e294a9-3ace-4428-a0d0-da84eecbeac1.png)

![image](https://user-images.githubusercontent.com/65976930/135077131-32329f0a-1bd5-48e1-8c05-0bf7fc8e1448.png)

Got the plan working in the local version , by wrapping line 24 in custom_landing_zones.tf in a try function

![image](https://user-images.githubusercontent.com/65976930/135077014-e1e0abeb-ff75-4ab1-9053-f7a79958ff0e.png)

**Comment by LaurentLesle** [comment]
I have updated with more screenshots to cover the subscriptions in the custom_landing_zones

**Comment by LaurentLesle** [comment]
Closing now
