### ISSUE TITLE
[Question] How can we share lzs across environments?

### ISSUE THREAD

**Issue by brk3** [Azure/caf-terraform-landingzones#284]
The hierarchy model and landing zone composition prescribed by CAF makes sense to me and am using this successfully. However, I haven't seen any examples of how to properly do shared services.

For example, suppose I deploy my network hub at `level2` in environment `X`. In `level3` of environment `X` I can reference that hub and peer to it, all good. But now a new team comes on board, and I'd like to deploy environment `Y`. 

How can I reference the hub from environment `Y`? Am I misunderstanding the purpose of environments?

**Comment by rdbartram** [comment]
If i understand you correctly, you can grab state from any environment as long as you share the same storage accounts for state.

When you call in your remote states below, you can just give the name of the file that needs to be read in. I haven't tried this but you could try using folder/name.tfstate to see if it calls in subdirectories so you maintain a bit of order.

Fundamentally the point is environments are a fictious construct and its really just a case of accessing the right state file in the storage account. Perhaps we can look at adding support for multiple storage accounts as right now everything is in one. 

```hcl
landingzone = {
  backend_type        = "azurerm"
  global_settings_key = "foundations"
  level               = "level2"
  key                 = "shared_services"
  tfstates = {
    foundations = {
      level   = "lower"
      tfstate = "caf_foundations.tfstate"
    }
    launchpad = {
      level   = "lower"
      tfstate = "launchpad_prod.tfstate"
    }
    launchpad_dev = {
      level   = "lower"
      tfstate = "launchpad_dev.tfstate"
    }
  }
}
```

**Comment by brk3** [comment]
Thanks for the reply @rdbartram. 

> you can grab state from any environment as long as you share the same storage accounts for state

Yes however this is exactly my point - for the states to be under the same set of storage accounts (launchpads), your Rover `-env` argument must be the same.

Suppose I have an Azure tenancy with 4 subscriptions under it, central, dev, test and prod. I first want to deploy the my foundations (level1) and shared_services (level2) to the central subscription. Lets suppose I use `rover [...] -env central`. Now in order to access these I also have to put all my dev/test/prod resources also under the storage accounts referred to by `-env central`, not ideal.

Intuitively I would want to have a separate Rover environment (and hence a separate set of storage  accounts) for each of dev/test/prod. But in this case which of them contains the shared services levels? And how can the other envs look up say the central hub if it's in a different set of launchpad storage accounts it has no reference to?

One way around this is to have a completely separate tenancy for each of dev/test/prod, implying a separate Rover env for each. Though I think during your live stream you said you generally dont like this model?

So in general my question is how are the community laying these out and what is the intended best practice for Rover environment structure.

**Comment by brk3** [comment]
Continued in https://github.com/aztfmod/rover/discussions/231

**Comment by gaoyarui** [comment]
asjuil.uliwsd.
