### ISSUE TITLE
Add support for postgresql_flexible_server

### ISSUE THREAD

**Issue by nusrath432** [Azure/caf-terraform-landingzones#285]
PR #286 

Add support for the following:

azurerm_postgresql_flexible_server
azurerm_postgresql_flexible_server_configuration
azurerm_postgresql_flexible_server_database
azurerm_postgresql_flexible_server_firewall_rule
    
Related: 
- https://github.com/aztfmod/terraform-provider-azurecaf/issues/137
- https://github.com/aztfmod/terraform-azurerm-caf/issues/841

**Comment by nusrath432** [comment]
@arnaudlh The Module is merged - if OK when can this be merged please

**Comment by arnaudlh** [comment]
Closing as included in 2203.0, thanks for the PR @nusrath432
