### ISSUE TITLE
[bug] Virtual network special subnet does not support AzureFirewallManagementSubnet

### ISSUE THREAD

**Issue by tenletters10** [Azure/caf-terraform-landingzones#302]
**Describe the bug**
The vnets module does not support a special subnet of "AzureFirewallManagementSubnet". It supports AzureBastionSubnet, AzureFirewallSubnet, GatewaySubnet, RouteServerSubnet which can be seen [here in the code](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/networking/virtual_network/subnet/subnet.tf#L8). 

This special subnet is used for [Forced Tunneling](https://docs.microsoft.com/en-us/azure/firewall/forced-tunneling) with Azure Firewall.

When you attempt to pass the special subnet of "AzureFirewallManagementSubnet" it appends the prefix name of "snet" which is invalid for the firewall to consume it. 

**To Reproduce**
  networking = {
    vnets = {
	  vnet_region1 = {
		resource_group_key = "reuse"
		vnet = {
		  name          = "test-vnet"
		  address_space = var.address_space
		}
		specialsubnets = {
			"AzureFirewallManagementSubnet" = {
			  "cidr" = ["10.200.95.128/26"]
			  "name" = "AzureFirewallManagementSubnet"
			},
			"AzureFirewallSubnet" = {
			  "cidr" = ["10.200.95.192/26"]
			  "name" = "AzureFirewallSubnet"
			}
		}
	  }
    }
  }

**Expected behavior**
Create a subnet named "AzureFirewallManagementSubnet" inside of the virtual network

**Screenshots**
![image](https://user-images.githubusercontent.com/22821988/149982262-ece6f8d2-f6f7-47fa-8d10-496f8e696045.png)

**Configuration (please complete the following information):**
 - OS and version: Windows 10 21H1
 - Version of the landing zone: 5.3.11

**Comment by arnaudlh** [comment]
thanks for reporting it @tenletters10. this would need to be fixed in the module: https://github.com/aztfmod/terraform-azurerm-caf

**Comment by LaurentLesle** [comment]
Fixed in 5.5.6

https://github.com/aztfmod/terraform-azurerm-caf/pull/1065/files#diff-8190a475d16e6a45e3e12c2da24a9b58670d1486bb7683b2657d999c92af3e60
