### ISSUE TITLE
[bug] Understanding Landing Zone Hierarchy file and folder was removed

### ISSUE THREAD

**Issue by LRomano72** [Azure/caf-terraform-landingzones#306]
**Describe the bug**
This file is the clearest document that shows that the point and layers of the CAF-TF are trying to do and it is very helpful but it was removed in the last merge, last found in Patch 5.5 branch:
https://github.com/Azure/caf-terraform-landingzones/blob/7b90a92959fe18275392d6c197f49497536c67d9/documentation/code_architecture/hierarchy.md
Is the last place I could find it and there is a lot of links that reference this file so if you are doing the "Starter" examples or trying to understand the CAF TF landing zones structure and methodology then this helps. Can it be returned?

**To Reproduce**
1. Go to https://github.com/Azure/caf-terraform-landingzones/blob/main/documentation/code_architecture/hierarchy.md
2. See 404

**Expected behavior**
Add the file back or fix the reference links documentation that matches the point the authors were trying to make

**Screenshots**

**Configuration (please complete the following information):**
 - OS and version: [e.g. Windows 10 1909]
 - Version of the rover[e.g. 22]
 - Version of the landing zone[e.g. 11]

**Additional context**

**Comment by arnaudlh** [comment]
hi @LRomano72 - we are progressively moving the reference docs to https://aztfmod.github.io/documentation/ that would consolidate, module, provider and LZ reference materials :)
