### ISSUE TITLE
Question: Will rover for level 3/4 app landing zones play well with terraform-azurerm-caf-enterprise-scale

### ISSUE THREAD

**Issue by jkewley** [Azure/caf-terraform-landingzones#307]
I'm looking at implementing enterprise scale for an organization and was hoping to use the [contoso template for enterprise scale](https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro) found in this repo as the starting point. My goal is to implement the level 0,1,2 baselines across multiple subscriptions, but the feeling I get from trying contoso is that it's not fully baked yet.

I'm wondering if we can leverage [terraform-azurerm-caf-enterprise-scale](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale) to stand up the [baseline ](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki) - management groups, policies, management, connectivity, and identity subscriptions, and then transition to using rover to deploy application landing zones for level 3 & 4.  

Specifically, I'm curious if Lvl 3/4 app landing zones stood up by rover will require visibility/access to the tf state from the contoso level 0, 1, 2 implementation, which wouldn't exist if we use terraform-azurerm-caf-enterprise-scale.

**Comment by arnaudlh** [comment]
We will be adding more docs soon for l3/l4 spin up, but this is already in 2203.0, stay tuned! https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro
