### ISSUE TITLE
[bug] branches missing

### ISSUE THREAD

**Issue by Justin-DynamicD** [Azure/caf-terraform-landingzones#310]
**Describe the bug**
According to multiple readme docs on using the landing zone framework, you should be checking out this code and setting the branch to a specific version:

https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/configuration/README.md#1-clone-the-public-landing-zones

and 

https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/platform/org-setup#switch-to-the-selected-landingzones-version

However, from what I can see, none of these branches exist in the repo, forcing me to run from main.

**Expected behavior**
the ability to select the landingzone version in order to test/ensure operational consistency

**Screenshots**

**Additional context**
if this info is out of date, a link to relevant/current documentation would be appreciated

**Comment by arnaudlh** [comment]
Work in progress here asnd release this week! please bear with us and thanks for the patience :)

**Comment by arnaudlh** [comment]
@Justin-DynamicD We hope the newly released 2203.0 makes things simpler and you like the new experience for gettings things started! https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro
