### ISSUE TITLE
Bugs / issues with the 2202 tag and contoso/enterprise scale

### ISSUE THREAD

**Issue by jkewley** [Azure/caf-terraform-landingzones#311]
I'm trying to implement the enterprise scale solution using rover, following the instructions found on [the docs site for this repo](https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro). I have run into several issues which make the consumption of an already complex implementation even more difficult. I'm surfacing them to help take down some barriers to entry for future consumers of this repo.

**Unnecessary ASR in Management**
[An ASR is defined in the management group](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/enterprise-scale/contoso/platform/management.yaml#L49), despite that [not being part of the ES reference architecture](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale#management-resources)

**Key vault policy for deploying using service account**
keyvault.tfvars.j2 accommodates/adds a [logged_in_user KV policy for access to key vault](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/platform/level0/launchpad/keyvaults.tfvars.j2#L24) if azuread_identity_mode == 'logged_in_user', but it should also accommodate 'service_principal' for cases when you run rover from local desktop while logged in as a service principal instead of a user

**Confusing (broken?) linkage between management.yaml and archetype_config_overrides.caf.platform.yaml**
`/templates/enterprise-scale/contoso/platform/management.yaml` has [the author's name](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/enterprise-scale/contoso/platform/management.yaml#L14) under subscriptions/management/diagnostic_log_analytics/region1/name [with a note above it](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/enterprise-scale/contoso/platform/management.yaml#L10) how important it is to update the related files. However, neither `/templates/enterprise-scale/contoso/platform/eslz/archetype_config_overrides.caf.platform.yaml` nor `custom_landing_zones.caf.platform.yaml` make reference to that value, and instead [appear to make reference to central_logs_sea](https://github.com/Azure/caf-terraform-landingzones/blob/5a9f9ac59b5a8c349dc79d5c8703951f87fa6518/templates/enterprise-scale/contoso/platform/eslz/archetype_config_overrides.caf.platform.yaml#L50) which is not present anywhere else in the branch. 

**Configuration (please complete the following information):**
 - OS and version:  **Windows 10 1909**
 - Version of the rover[e.g. 22]: **aztfmod/rover:1.1.3-2201.2106**
 - Version of the landing zone[e.g. 11] **tag 2202**

**Comment by arnaudlh** [comment]
hi @jkewley, we have improved the onboarding experience with the release 2203.0 . You can get started there: https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro . Hope it make things more streamlined!
