### ISSUE TITLE
Add more <replaces> in configure file

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/caf-terraform-landingzones#325]
Could more <replace> files be added in configure file

https://github.com/Azure/caf-terraform-landingzones/blob/864b800f7022e2feff91f89e8c9cc416d95b4b29/templates/enterprise-scale/contoso/platform/single_subscription/contoso.caf.platform.yaml#L21

https://github.com/Azure/caf-terraform-landingzones/blob/864b800f7022e2feff91f89e8c9cc416d95b4b29/templates/enterprise-scale/contoso/platform/single_subscription/contoso.caf.platform.yaml#L29

https://github.com/Azure/caf-terraform-landingzones/blob/864b800f7022e2feff91f89e8c9cc416d95b4b29/templates/enterprise-scale/contoso/platform/single_subscription/contoso.caf.platform.yaml#L32

**Comment by arnaudlh** [comment]
hi @EelcoLabordus - this is work in progress and will be released soon! thanks for the issue!

**Comment by arnaudlh** [comment]
Closing as merge, hope you like the new experience for gettings things started! https://aztfmod.github.io/documentation/docs/enterprise-scale/landingzones/eslz-intro
