### ISSUE TITLE
[bug] Error: Value must be a valid UUID

### ISSUE THREAD

**Issue by huqianghui** [Azure/caf-terraform-landingzones#328]
**Describe the bug**

I modified the file--/tf/caf/definitions/contoso.caf.platform.yaml
  enable_azuread_groups: false
  enable_azuread_applications: false

Ignite the configuration, the error appears too.

Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["caf_platform_maintainers"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 

**To Reproduce**
1. git clone <replace> /tf/caf/landingzones
cd /tf/caf/landingzones
git pull
git checkout aci_network
2. rover login -t <replace> -s <replace>

rover ignite \
  --playbook /tf/caf/landingzones/templates/platform/ansible.yaml \
  -e base_templates_folder=/tf/caf/landingzones/templates/platform \
  -e resource_template_folder=/tf/caf/landingzones/templates/resources \
  -e config_folder=/tf/caf/definitions/single_subscription \
  -e landingzones_folder=/tf/caf/landingzones
3. rover \
  -lz /tf/caf/landingzones/caf_launchpad \
  -var-folder /tf/caf/configuration/dev1/level0/launchpad \
  -tfstate_subscription_id f35935fc-8357-49da-a453-7863b85baf40 \
  -target_subscription f35935fc-8357-49da-a453-7863b85baf40 \
  -tfstate caf_launchpad.tfstate \
  -launchpad \
  -env dev1 \
  -level level0 \
  -p ${TF_DATA_DIR}/caf_launchpad.tfstate.tfplan \
  -a plan

**Expected behavior**

No errors.

**Configuration (please complete the following information):**
 - OS and version: MacOS Big Sur Version 11.6.4
 - Version of the rover: aztfmod/rover:1.1.6-2202.2503
 - Version of the landing zone[e.g. 11]: 1.2.15

**Additional context**
Terraform has been successfully initialized!
Line 101 - Terraform init return code 0
calling plan
@calling plan
running terraform plan with -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_api_permissions.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_applications.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_group_members.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_groups.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_roles.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/azuread_service_principals.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/dynamic_keyvault_secrets.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/global_settings.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/keyvault_access_policies.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/keyvaults.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/landingzone.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/resource_groups.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/role_mapping.tfvars -var-file /tf/caf/configuration/dev1/level0/launchpad/storage_accounts.tfvars
 -TF_VAR_workspace: tfstate
 -state: /home/vscode/.terraform.cache/launchpad/dev1/tfstates/level0/tfstate/caf_launchpad.tfstate
 -plan:  /home/vscode/.terraform.cache/launchpad/dev1/tfstates/level0/tfstate/caf_launchpad.tfplan
/tf/caf/landingzones/caf_launchpad
Running Terraforn plan...
@calling terraform_plan -- azurerm
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["caf_platform_maintainers"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["eslz"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["identity"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["caf_platform_contributors"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["subscription_creation_platform"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["subscription_creation_landingzones"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["management"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["connectivity"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
╷
│ Error: Value must be a valid UUID
│ 
│   with module.launchpad.module.azuread_groups["level0"].azuread_group.group,
│   on /home/vscode/.terraform.cache/launchpad/dev1/modules/launchpad/modules/azuread/groups/group.tf line 6, in resource "azuread_group" "group":
│    6:   owners = coalescelist(
│    7:     try(tolist(var.azuread_groups.owners), []),
│    8:     [
│    9:       var.client_config.object_id
│   10:     ]
│   11:   )
│ 
╵
Terraform plan return code: 1
Error on or near line 391: Error running terraform plan; exiting with status 1

**Comment by arnaudlh** [comment]
hi @huqianghui I suspect this would be addressed by this fix: https://github.com/aztfmod/terraform-azurerm-caf/pull/925 - we are validating it and will update the module logic with it soon.

**Comment by huqianghui** [comment]
> hi @huqianghui I suspect this would be addressed by this fix: [aztfmod/terraform-azurerm-caf#925](https://github.com/aztfmod/terraform-azurerm-caf/pull/925) - we are validating it and will update the module logic with it soon. If you have a dev environment including a local version of the module, happy to get your feedback if it fixes your problem!

yes, I pulled the source code to local and replace the code.
it works.
Thanks @arnaudlh .

**Comment by arnaudlh** [comment]
thanks for your rapid feedback @huqianghui, we definitely will include the fix in next rel!

**Comment by ctahok** [comment]
Is there a fix yet?

**Comment by ronaldbok** [comment]
Is there a fix yet?

**Comment by ronaldbok** [comment]
> > hi @huqianghui I suspect this would be addressed by this fix: [aztfmod/terraform-azurerm-caf#925](https://github.com/aztfmod/terraform-azurerm-caf/pull/925) - we are validating it and will update the module logic with it soon. If you have a dev environment including a local version of the module, happy to get your feedback if it fixes your problem!
> 
> yes, I pulled the source code to local and replace the code. it works. Thanks @arnaudlh .

I changed the code. But on witch file did you change the code. The Error accurse on a file in the Cache folder. so this file is generated and modify this one is pointless becourse it will be overwritten at the moment you run the script again.
