### ISSUE TITLE
Cannot deploy the Bastion when the VNet isn't deployed in the same deployment.

### ISSUE THREAD

**Issue by EelcoLabordus** [Azure/caf-terraform-landingzones#335]
I'm trying to deploy a bastion configuration using Rover version aztfmod/rover:1.1.6-2202.2503. When I do a plan of the configuration i got a error  "The given key does not identify an element in this collection value."

The VNet has been deployed in the networking_hub.

What am i doing wrong?

Error
╷
│ Error: Invalid index
│ 
│   on /home/vscode/.terraform.cache/cmis/rover_jobs/20220315095050382409100/modules/solution/bastion_service.tf line 33, in resource "azurerm_bastion_host" "host":
│   33:     subnet_id            = local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][try(each.value.vnet.vnet_key, each.value.vnet_key)].subnets[try(each.value.vnet.subnet_key, each.value.subnet_key)].id
│     ├────────────────
│     │ each.value is object with 7 attributes
│     │ each.value.vnet_key is "hub_re1"
│     │ local.client_config.landingzone_key is "networking_bastion"
│     │ local.combined_objects_networking is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.

Config files:
**bastion_hosts.tfvars**

```
bastion_hosts = {
  bastion_hub_re1 = {
    name               = "bas-conn-prod-we-001"
    region             = "region1"
    resource_group_key = "rg-bastion"
    vnet_key           = "hub_re1"
    lz_key             = "networking_hub"
    subnet_key         = "AzureBastionSubnet"
    public_ip_key      = "bastion_host_re1"
    # you can setup up to 5 profiles
  }
}
```

**landingzone.tfvars**
```
#Default landing zone configuration for networking_bastion configuration.
landingzone = {
  backend_type        = "azurerm"
  global_settings_key = "management"
  level               = "level2"
  key                 = "networking_bastion"
  #What previous deployment needs to be added to extract information from.
  tfstates = {
    management = {
      level   = "lower"
      tfstate = "management.tfstate"
    }
    networking_hub = {
      level   = "current"
      tfstate = "networking_hub.tfstate"
    }
  }
}
```

**Comment by arnaudlh** [comment]
Thanks for opening the issue @EelcoLabordus, this should be address with module 5.5.4, do you have possibility to try it out and confirm it solves your issue? 
Thanks 
Arnaud

**Comment by EelcoLabordus** [comment]
Hey Arnaud,

I did try it again but it still doesn't work, i don't know if i did it correct:

Upgrading modules...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for dynamic_keyvault_secrets...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for solution...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_custom_scriptextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_diagnostics...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_microsoft_azure_domainjoin...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_monitoring_agent...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_session_host_dscextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vmss_extension_custom_scriptextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vmss_extension_microsoft_azure_domainjoin...
Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding hashicorp/tls versions matching "~> 3.1.0"...
- Finding hashicorp/null versions matching "~> 3.1.0"...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Finding hashicorp/external versions matching "~> 2.2.0"...
- Finding latest version of hashicorp/time...
- Finding hashicorp/azuread versions matching "~> 1.4.0"...
- Finding hashicorp/azurerm versions matching "~> 2.88.1"...
- Finding aztfmod/azurecaf versions matching "~> 1.2.0"...
- Finding latest version of hashicorp/local...
- Using previously-installed hashicorp/azurerm v2.88.1
- Using previously-installed hashicorp/local v2.2.2
- Using previously-installed hashicorp/random v3.1.2
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed hashicorp/external v2.2.2
- Using previously-installed hashicorp/azuread v1.4.0
- Using previously-installed aztfmod/azurecaf v1.2.16
- Using previously-installed hashicorp/tls v3.1.0
- Using previously-installed hashicorp/null v3.1.1
Terraform has been successfully initialized!
Terraform init return code 0
calling plan
@calling plan
running terraform plan with -var-file /tf/caf/configuration/XXXX/platform/level2/networking/bastion/bastion_hosts.tfvars -var-file /tf/caf/configuration/XXXXX/platform/level2/networking/bastion/landingzone.tfvars -var-file /tf/caf/configuration/XXXXX/platform/level2/networking/bastion/public_ip_addresses.tfvars -var-file /tf/caf/configuration/XXXXXX/platform/level2/networking/bastion/resource_groups.tfvars -parallelism 30
 -TF_VAR_workspace: tfstate
 -state: /home/vscode/.terraform.cache/xxxxxxx/rover_jobs/20220330092141826124200/tfstates/level2/tfstate/networking_bastion.tfstate
 -plan:  /home/vscode/.terraform.cache/xxxxxxx/rover_jobs/20220330092141826124200/tfstates/level2/tfstate/networking_bastion.tfplan
/tf/caf/landingzones/caf_solution
Running Terraforn plan...
@calling terraform_plan -- azurerm
╷
│ Error: Invalid index
│ 
│   on /home/vscode/.terraform.cache/cmis/rover_jobs/20220330092141826124200/modules/solution/bastion_service.tf line 33, in resource "azurerm_bastion_host" "host":
│   33:     subnet_id            = local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][try(each.value.vnet.vnet_key, each.value.vnet_key)].subnets[try(each.value.vnet.subnet_key, each.value.subnet_key)].id
│     ├────────────────
│     │ each.value is object with 7 attributes
│     │ each.value.vnet_key is "hub_re1"
│     │ local.client_config.landingzone_key is "networking_bastion"
│     │ local.combined_objects_networking is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
Terraform plan return code: 1
Error on or near line 391: Error running terraform plan; exiting with status 1

@calling clean_up_variables
cleanup variables
clean_up backend_files

**Comment by EelcoLabordus** [comment]
Hey Arnaud,

I did try it again but it still doesn't work, i don't know if i did it correct:

```
Upgrading modules...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for dynamic_keyvault_secrets...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for solution...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_custom_scriptextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_diagnostics...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_microsoft_azure_domainjoin...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_monitoring_agent...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vm_extension_session_host_dscextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vmss_extension_custom_scriptextension...
Downloading registry.terraform.io/aztfmod/caf/azurerm 5.5.5 for vmss_extension_microsoft_azure_domainjoin...
Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding hashicorp/tls versions matching "~> 3.1.0"...
- Finding hashicorp/null versions matching "~> 3.1.0"...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Finding hashicorp/external versions matching "~> 2.2.0"...
- Finding latest version of hashicorp/time...
- Finding hashicorp/azuread versions matching "~> 1.4.0"...
- Finding hashicorp/azurerm versions matching "~> 2.88.1"...
- Finding aztfmod/azurecaf versions matching "~> 1.2.0"...
- Finding latest version of hashicorp/local...
- Using previously-installed hashicorp/azurerm v2.88.1
- Using previously-installed hashicorp/local v2.2.2
- Using previously-installed hashicorp/random v3.1.2
- Using previously-installed hashicorp/time v0.7.2
- Using previously-installed hashicorp/external v2.2.2
- Using previously-installed hashicorp/azuread v1.4.0
- Using previously-installed aztfmod/azurecaf v1.2.16
- Using previously-installed hashicorp/tls v3.1.0
- Using previously-installed hashicorp/null v3.1.1
Terraform has been successfully initialized!
Terraform init return code 0
calling plan
@calling plan
running terraform plan with -var-file /tf/caf/configuration/XXXX/platform/level2/networking/bastion/bastion_hosts.tfvars -var-file /tf/caf/configuration/cmis/platform/level2/networking/bastion/landingzone.tfvars -var-file /tf/caf/configuration/cmis/platform/level2/networking/bastion/public_ip_addresses.tfvars -var-file /tf/caf/configuration/cmis/platform/level2/networking/bastion/resource_groups.tfvars -parallelism 30
 -TF_VAR_workspace: tfstate
 -state: /home/vscode/.terraform.cache/cmis/rover_jobs/20220330092141826124200/tfstates/level2/tfstate/networking_bastion.tfstate
 -plan:  /home/vscode/.terraform.cache/cmis/rover_jobs/20220330092141826124200/tfstates/level2/tfstate/networking_bastion.tfplan
/tf/caf/landingzones/caf_solution
Running Terraforn plan...
@calling terraform_plan -- azurerm
╷
│ Error: Invalid index
│ 
│   on /home/vscode/.terraform.cache/cmis/rover_jobs/20220330092141826124200/modules/solution/bastion_service.tf line 33, in resource "azurerm_bastion_host" "host":
│   33:     subnet_id            = local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][try(each.value.vnet.vnet_key, each.value.vnet_key)].subnets[try(each.value.vnet.subnet_key, each.value.subnet_key)].id
│     ├────────────────
│     │ each.value is object with 7 attributes
│     │ each.value.vnet_key is "hub_re1"
│     │ local.client_config.landingzone_key is "networking_bastion"
│     │ local.combined_objects_networking is object with 3 attributes
│ 
│ The given key does not identify an element in this collection value.
╵
Terraform plan return code: 1
Error on or near line 391: Error running terraform plan; exiting with status 1

@calling clean_up_variables
cleanup variables
clean_up backend_files
```

**Comment by arnaudlh** [comment]
hi @EelcoLabordus, you need to disambiguate the lz_key and put it in the vnet object, that way, you can also specify a remote key for the public_ip address also: 

```
bastion_hosts = {
  bastion_hub_re1 = {
    name               = "bastion-rg1"
    region             = "region1"
    resource_group_key = "test_bastion"
    vnet = {
      vnet_key           = "hub_re1"
      lz_key             = "launchpad"
    }
    subnet_key         = "AzureBastionSubnet"
    public_ip = {
      key      = "bastion_host_rg1"
      #lz_key
    }
   }

}
```

Let me know if that solves your issue.

**Comment by EelcoLabordus** [comment]
Thanks @arnaudlh it is working, maybe update the example also.
