### ISSUE TITLE
What’s the difference between this repo and Azure/terraform-azurerm-caf-enterprise-scale

### ISSUE THREAD

**Issue by binaryPUNCH** [Azure/caf-terraform-landingzones#371]
Hi! I’m confused what the difference is between this repo and https://github.com/Azure/terraform-azurerm-caf-enterprise-scale

They are both managed by Microsoft so can someone clarify what’s the difference and what’s best to use for a large org 500+ workloads.

Thanks!

**Comment by arnaudlh** [comment]
hi @binaryPUNCH, I believe this should help you: https://docs.microsoft.com/en-gb/azure/cloud-adoption-framework/ready/landing-zone/deploy-landing-zones-with-terraform

**Comment by binaryPUNCH** [comment]
Thanks, @arnaudlh, I missed that page somehow!
