### ISSUE TITLE
[feature] Support for multi-subscriptions deployment model

### ISSUE THREAD

**Issue by arnaudlh** [Azure/caf-terraform-landingzones#42]
Coming up with an onboarding model to manage multiple subscriptions and the related security considerations for the various landing zones models. 

Minimum scenarios to cover:
- add an existing subscription to the reference model
- onboard management groups and policies.
- select the right subscription for a particular deployment - linked to https://github.com/aztfmod/rover/issues/37 
- [optional] provisioning from EA, onboarding from other channels.

**Comment by arnaudlh** [comment]
Adding link to rover issue: https://github.com/aztfmod/rover/issues/37

**Comment by patpicos** [comment]
@arnaudlh is there a roadmap / timeline for this capability? Very keen on this feature

**Comment by arnaudlh** [comment]
hi @patpicos we are actively working on it now and are targeting the 2008 (august) release, if everything goes according to plans.

**Comment by picardsrcd** [comment]
any update?

**Comment by arnaudlh** [comment]
> any update?

yes in this month's release, if you really cant wait its here: https://github.com/Azure/caf-terraform-landingzones/tree/multisub but its still preliminary and low doc :)
