### ISSUE TITLE
[feature] Implement Azure Monitor - Service Health Alerts

### ISSUE THREAD

**Issue by benhurjoel** [Azure/caf-terraform-landingzones#50]
**Is your feature request related to a problem? Please describe.**
Would like to add a feature enhancement of Monitoring Module in to the CAF Foundations. The Module may include the monitoring and alerts elements that may be needed in the Landing Zone. 

**Describe the solution you'd like**

_Planned inclusion:_

landingzone_caf_foundations
|_ blueprint_foundations_monitoring  --> New
	|_ Service health Alerts

_An alert/set of alerts to be triggered in the event of :_
- Service Issue  (Global and Region wide)
- Planned maintenance
- Health Advisories
- Security Advisories

_Components to be created:_
- An action group.
- Set of alert rules

**Pseudo Code**
resource "azurerm_monitor_action_group" "ag1" {
  name                = var.name
  resource_group_name = var.rg
  short_name          = var.shortname
  enabled =  #boolean_value from variable set

  dynamic "email_receiver" {
  for_each = enable_email_alert == false ? [] : [1] # decider from variable set
  content {
   #from variable set
   }
  }

  dynamic "sms_receiver" {
  for_each =  enable_sms_alert == false? [] : [1] # decider from variable set
  content {
 #from variable set
   }
  }

  dynamic "webhook_receiver" {
  for_each = enable_webhook_trigger == false ? [] : [1]  # decider from variable set
  content {
 #from variable set
    }
  }

  dynamic "arm_role_receiver" {
  for_each = enable_arm_role_alert == false ? [] : [1] # decider from variable set
  content {
 #from variable set
   }
  }

} 

#Due to the current limitations of 'azurerm_monitor_activity_log_alert' Resource, implementing this alert using ARM Template.

resource "azurerm_template_deployment" "alert1" {
  name                = "random_name"
  resource_group_name = var.rg

  template_body = file("${path.module}/filename.json")
  parameters = {
    "name"              =  "name"
    "actionGroups_name" = azurerm_monitor_action_group.ag1.name
    "region"            = "${join(",", var.alert_settings.service_health_alerts.location)}" #from variable set
  }
  deployment_mode = "Incremental"

}

**Reference**
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7392
https://docs.microsoft.com/en-us/azure/service-health/service-health-overview
https://www.terraform.io/docs/providers/azurerm/r/monitor_activity_log_alert.html

**Comment by arnaudlh** [comment]
This has been added to [core module](https://github.com/aztfmod/terraform-azurerm-caf) - need to implement into ALZ scenario.
