### ISSUE TITLE
workspace file seems to be missing.

### ISSUE THREAD

**Issue by neop26** [Azure/caf-terraform-landingzones#51]
Hi, 

In order to start the workspace in a remote container we needed the workspace file which was there in the last version. This seems to be missing. Once the current version was cloned, I copied the old workspace file over.

This is part of the steps involved in "Getting Started".

**Comment by Masahigo** [comment]
I stumbled on the same issue just now. The workspace file is gone from `master` branch.

**Comment by LaurentLesle** [comment]
Hi @neop26 and @Masahigo can you explain how you are using workspace? it's been removed as initially used to set the "\n" setting for common experience between windows, mac and linux. It's been moved to the devcontainer.json in the settings section.
Have you tried the option Remote-Containers: Reopen in containers

**Comment by arnaudlh** [comment]
@neop26 @Masahigo @LaurentLesle - doc updated to reflect the change!

**Comment by neop26** [comment]
Perfect that worked  - Reopen in Containers.
