### ISSUE TITLE
2007 tfstate RG is hardcoded for southeastasia

### ISSUE THREAD

**Issue by bmaltais** [Azure/caf-terraform-landingzones#66]
**Describe the bug**
The current 2007 launchpad code is positionning the tfstate resource group in southeastasia as can be seen below

```json
tfstate     = {
    name        = "launchpad-tfstates"
    location    = "southeastasia"
    useprefix   = true
    max_length  = 40
  }
```

**To Reproduce**
Deploy the launchpad

**Expected behavior**
RG should be in user specified region

**Configuration (please complete the following information):**
 - LZ release 2007

**Comment by bernardmaltais** [comment]
Proposed fix: https://github.com/Azure/caf-terraform-landingzones/pull/69

Sorry... this fix include the changes for the other proposed change to keyvault access policy.

**Comment by arnaudlh** [comment]
Closing as fixed in 2010
