### ISSUE TITLE
Describe required privileges to deploy the foundation

### ISSUE THREAD

**Issue by vrdse** [Azure/caf-terraform-landingzones#72]
First and foremost thank you for the amazing work! However, I tried to deploy the foundation in my MSDN subscription using Visual Studio Code Spaces.

`/tf/rover/rover.sh -lz /tf/caf/landingzones/launchpad -a apply -launchpad -var location=westus`

I get the following error:

> Error: graphrbac.ApplicationsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-08-10T09:46:37","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"guid"}}]
> 
>   on /home/vscode/.terraform.cache/modules/azure_applications/terraform-azuread-caf-aad-apps-1.0.0/aad_application.tf line 38, in resource "azuread_application" "aad_apps":
>   38: resource "azuread_application" "aad_apps" {

I assume I miss the privileges to create new applications in AAD, which is fine. My request is, to add the required minimal privileges to deploy the foundation to the README. This would ease initial access to the CAF deployment for everyone.

**Comment by anttipo** [comment]
Has something changed significantly on the tf module side to cause this? I am facing the same issue but I do remember that this was not an issue before with previous version of rover/launchpads.

Global Administrator will technically work but is not a solution for long term and enterprise use.

**Comment by anttipo** [comment]
@arnaudlh any thoughts?

**Comment by LaurentLesle** [comment]
Initial response - https://github.com/Azure/caf-terraform-landingzones/blob/master/documentation/enterprise/bootstrap_account_provisioning.md
