### ISSUE TITLE
[bug] specialsubnets is required

### ISSUE THREAD

**Issue by xpillons** [Azure/caf-terraform-landingzones#78]
**Describe the bug**
`specialsubnets` has to be specified even if empty, this is confusing when starting from scratch

**To Reproduce**
define a vnet without `specialsubnets`

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS and version: Windows 10 + WSL2
 - Version of the rover: aztfmod/rover:2009.0210
 - Version of the landing zone[e.g. 11]

**Additional context**

**Comment by xpillons** [comment]
should be a feature request instead of a bug I guess

**Comment by arnaudlh** [comment]
hi @xpillons this is fixed in vnext/0.4 thanks for your feedback
