### ISSUE TITLE
Storage Blob Data Contributor is missing on the service principal created in Launchpad.

### ISSUE THREAD

**Issue by sunnynazar** [Azure/caf-terraform-landingzones#82]
**Describe the bug**
During launchapad execution, we create a service principal which is then used in next landing zones. Currently i see it has Storage Blob Data Contributor missing with scope tf states resource group. If we deploy landing zone level 1  and then try to destroy it , it complains about the missing role as shown in below.

**To Reproduce**
rover -lz /tf/caf/landingzones/landingzone_caf_foundations -a destroy

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/40354767/94413743-c5702b80-017b-11eb-9840-2bca8d32ca4a.png)

**Configuration**

Version of the rover: aztfmod/rover:2009.0210
Version of the landing zone : v8.0.2001

**Possible Solution**
Solution should be to add this role to the service principal in launchpad like we do for the current user in launchpad folder in storage.tf file.

Sample resource block could be like this.

resource "azurerm_role_assignment" "ad_container_role" {
  for_each                     = var.blobrole
  scope                         = azurerm_resource_group.rg["tfstate"].id
  role_definition_name = each.value.role_definition_name
  principal_id                = module.azure_applications.aad_apps[each.value.aad_app_key].azuread_service_principal.object_id
}

And in auto.tfvars config could be like.

blobrole = {
  roles = {
    role_definition_name = "Storage Blob Data Contributor"
    aad_app_key          = "caf_launchpad_level0"
  }
} 

**Note** : if you agree on this bug and proposed solution, i could merge the code with pull request.

**Comment by arnaudlh** [comment]
hi @sunnynazar - might be related to #84 please let us know.

**Comment by sunnynazar** [comment]
No - this is not related to #84.
Because all containers were created successfully in this scenario.

**Comment by LaurentLesle** [comment]
Closing now as working
