### ISSUE TITLE
rover landingzone terraform destroy not working with service principal

### ISSUE THREAD

**Issue by sunnynazar** [Azure/caf-terraform-landingzones#83]
**Describe the bug**

I have started the azure session with service principal and created resources in launchpad.But when i try to destroy the resources created with the same service principal , rover complains that it's not the same user which initialized the launchpad landing zone.

**To Reproduce**
start the azure session using service principal .
      az login --service-principal -u '$(ARM_CLIENT_ID)' -p '$(ARM_CLIENT_SECRET)' --tenant '$(ARM_TENANT_ID)'
      az account set -s $(ARM_SUBSCRIPTION_ID)
      export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
      export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
      export ARM_TENANT_ID=$(ARM_TENANT_ID)
      export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)

rover -lz /tf/caf/landingzones/launchpad/ -a apply -launchpad -env Dev
rover -lz /tf/caf/landingzones/launchpad/ -a destroy -launchpad -env Dev

**Expected behavior**
destroy the resources and no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/40354767/94542237-da66c080-0248-11eb-92a3-02b11948aff3.png)

**Configuration**
Version of the rover: aztfmod/rover:2009.0210
Version of the landing zone : v8.0.2001

**Comment by LaurentLesle** [comment]
Make sure the SP is created as follow:
https://github.com/Azure/caf-terraform-landingzones/blob/master/documentation/enterprise/bootstrap_account_provisioning.md
