### ISSUE TITLE
Docker Volume UI asks to share full drive

### ISSUE THREAD

**Issue by anand2803** [Azure/caf-terraform-landingzones#86]
**Describe the bug**
Unable to Create CAF by following documentation below link
https://github.com/Azure/caf-terraform-landingzones/blob/master/documentation/getting_started/getting_started.md
Able to test remote container execution by creating sample vscode-remote-try-node , which means setup like Docker , Vscode extension etc are all fine.

**To Reproduce**

**Expected behavior**
When Running Remote-Container : Reopen in Container , I get error message as mentioned in screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/24716752/94997353-28bcec00-05c8-11eb-9252-bca3af92a7d4.png)
![image](https://user-images.githubusercontent.com/24716752/94997367-370b0800-05c8-11eb-8400-6e75cd28e597.png)

**Configuration (please complete the following information):**
 - OS and version: Windows 10 1803
 - Version of the rover:  aztfmod/rover:2009.0210
 - Version of the landing zone[e.g. 11]

**Additional context**
Docker > setting > resources > File Sharing is configured. ( included entire D: and also the folder where source code is kept

**Comment by anand2803** [comment]
I got it working by Sharing my C drive in Docker > Setting > Preference > File Sharing .
Question is why I need to share my C drive if my Source Code is on D drive which I have already shared.

**Comment by arnaudlh** [comment]
hi @anand2803 thanks for sharing the current status. we will investigate on this one.

**Comment by arnaudlh** [comment]
closing as by default on docker version.
