### ISSUE TITLE
[question] which branch is recomended?

### ISSUE THREAD

**Issue by Justin-DynamicD** [Azure/caf-terraform-landingzones#89]
I'm simply curious which branch is recomended for use by general public? In many projects master is not considered a production state, and one should rely on tags/releases. I also noticed some of the bugs issues are around version specific branches like 0.4.  

What is the recomended model at this time?

**Comment by arnaudlh** [comment]
Stable is master, 0.4 is still under dev on which we are spending most of our time, I'd recommend using this one if your project is just starting.
