### ISSUE TITLE
[feature] Better More complete Documentation

### ISSUE THREAD

**Issue by Justin-DynamicD** [Azure/caf-terraform-landingzones#90]
I'm really struggling to get use of these "landingzones" outside of the very simple "getting started" example.  A large chunk of this is a lack of clear documentation on how things are structured that is unique to the TF launchpad itself as well as how the rover expects to find data structured, leverages/detects state info, etc.  AKA I cant read the CAF documentation for insight as this all hovers around TF/rover specific implimentation.

For example, "landingzones" apear to be terraform plans instead of modules, and its expected that you manually call a tf_var with desired settings from another directory?  Is that correct?  Rover seems to scan for workspaces, but I'm not sure what it does with that info. If you don't select `-env prod` or whatever everythign defaults into a "sandpit" container... but the significance isn't spelled out. Can you extend one launchpad to handle new levels/subscriptions so it acts as a shared tfstate repo?  Should every level/subscription have its own launchpad? Theres a nice drawing explaining why there are 4 levels but how do you configure vars to build those containers, set the permissions, etc?  Oh, and if I cd into a directory and run rover -lz ./ it's completely unable to figure out the landingzone name, so apprently dont do that.

Then I try to build a new "landingzone" which again ... seems liek a generic terraform plan.  How do I make sure the new plan runs at the right level[0...4]? How do I ensure Rover pics the name up correctly, finds the keyvault with all the secrets, and runs under the right app context? How is this secured?

I'm not asking for all of this to be answered in this thread, more pointing out that there is a massive hole of information here that can only be solved with lots of trial and error (and error, and error). WIthin a few minutes of fumbling with `rover [insert massive string of vars here]` I give up and just fall back on `terraform plan` and move on, becuase that just works.  I feel like im constantly fighting rover here .... when its supposed to be making things easier (like letting me not think about statefiles).

**Comment by arnaudlh** [comment]
hi @Justin-DynamicD I totally agree with you on the onboard experience and we are working on it at this very moment with videos and documentation, so please bear with us a couple more days. I will post here things as they are published!

**Comment by Justin-DynamicD** [comment]
Don't you tease me now (ok a little teasing is ok).

This big problem I have right now is most videos just walk throug hthe quick start guide (look i can standup in the default southeastasia!), so something that takes a bit more care to explain the expected workflow would be huge.

One of my biggest concerns right now: upgrading launchpad.  Its not a module ... so IM concerned about how easy it will be to clone/merge code changes instead of making it a module so I can just version lock it instead (oh 0.4 is out?  Lets update the version tag and try it out).

**Comment by kiebre92** [comment]
Agree with this too, i'm very interested in using the CAF terraform landingzone concept with a new greenfield deployment, but struggling a little with the documentation, or lack thereof.

One of the fairly well explained concepts is the different tiers (level 0 - 4) which in principle sounds great, I'm struggling a little to grasp to concept of how to do that in practice. The current repo has launchpad (Level 0?), caf_foundations (Level 1?) and networking (Level 2?), but lacks any examples of Level 3 or 4, which would be extremely useful given this is potentially where the bulk of resources and TF code would be deployed.

**Comment by arnaudlh** [comment]
Hi folks, we added couple of documentation additions in this months release, we also have published a starter repository that illustrates the creation of a configuration repository: https://github.com/Azure/caf-terraform-landingzones-starter. please keep on reviewing and commenting to make it better!
